name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  ZIG_VERSION: 0.15.2
  NODE_VERSION: 18

jobs:
  publish:
    name: Build Web Frontend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.15.2

    - name: zig test
      run: zig build test

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: deploy-server 
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1
      env:
        GIT_HASH: ${{ github.sha }}
      with:
        host: ${{ secrets.HOST }}
        username: root 
        key: ${{ secrets.KEY }}
        envs: GIT_HASH
        script: |
          cd /build/community-crossword
          git fetch
          git checkout $GIT_HASH
          source /app/community-crossword.env
          docker compose -f deploy.yml up --build --force-recreate --no-deps  -d community-crossword

    - name: Type check and build
      run: VITE_WS_URL='wss://community-crossword.com' VITE_APP_URL='https://community-crossword.com'  VITE_APP_S3='https://crossword.sfo3.digitaloceanspaces.com' npm run build

    - name: Upload to Itch.io
      if: github.ref == 'refs/heads/main'
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        ./butler -V
        ./butler login
        ./butler push dist mpollind/community-crossword:html
