name: CI

on:
  push:
    branches: [main]

env:
  ZIG_VERSION: 0.15.2
  NODE_VERSION: 18

jobs:
  deploy:
    name: deploy 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: deploy-server 
      uses: appleboy/ssh-action@v1
      env:
        GIT_HASH: ${{ github.sha }}
      with:
        host: ${{ secrets.HOST }}
        username: root 
        key: ${{ secrets.KEY }}
        envs: GIT_HASH
        script: |
          cd /build/community-crossword
          git fetch
          git checkout $GIT_HASH
          docker compose --env-file /app/community-crossword.env -f deploy.yml up --build --force-recreate --no-deps -d 

    - name: Type check and build
      run: VITE_WS_URL='wss://community-crossword.com' VITE_APP_URL='https://community-crossword.com'  VITE_APP_S3='https://crossword.sfo3.digitaloceanspaces.com' npm run build

    - name: Upload to Itch.io
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      run: |
        curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/15.24.0/archive/default
        unzip butler.zip
        chmod +x butler
        ./butler -V
        ./butler login
        ./butler push dist mpollind/community-crossword:html
